name: Publish

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [trigger-publish]
  workflow_dispatch:

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '#Release')) || (github.event_name != 'push')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - run: git submodule update --init ./central
      - run: |
          cd central
          git submodule update --init ./scaffold
          cd ..
      - run: npm run package

      - name: Get version from package.json
        id: artifact
        run: |
          pacname=$(jq -r .name package.json)
          version=$(jq -r .version package.json)
          echo "pacname=$pacname" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV

      - name: Prepare artifact name
        id: vsix_name
        run: |
          pacname=${{ env.pacname }}
          version=${{ env.version }}
          latest_vsix="${pacname}-vsce_latest.vsix"
          version_vsix="${pacname}-vsce_v${version}.vsix"
          packaged_vsix="${pacname}-${version}.vsix"

          echo "packaged_vsix=$packaged_vsix" >> $GITHUB_ENV
          echo "version_vsix=$version_vsix" >> $GITHUB_ENV
          echo "latest_vsix=$latest_vsix" >> $GITHUB_ENV

          mkdir -p version
          cp "$packaged_vsix" "version/$version_vsix"

          mkdir -p latest
          cp "$packaged_vsix" "latest/$latest_vsix"

      - name: Publish release (version tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          name: Release v${{ env.version }}
          body_path: ./RELEASE.md
          files: version/**
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release (latest tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Release latest
          body_path: ./RELEASE.md
          files: latest/**
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish on Open VSX Registry
        id: ovsx
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.XCSS_OVSX }}
          extensionFile: ${{ env.packaged_vsix }}
        continue-on-error: true

      - name: Publish on VS Code Marketplace
        id: vsce
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ env.packaged_vsix }}
        continue-on-error: true

      - name: Check if any step failed
        run: |
          if [[ "${{ steps.ovsx.outcome }}" == "failure" || "${{ steps.vsce.outcome }}" == "failure" ]]; then
            echo "Some steps failed."
            exit 1
          fi
