name: Publish VSCode

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - run: git submodule update --init ./core

      - run: npm run package

      - name: Get version from package.json
        id: artifact
        run: |
          pacname=$(jq -r .name package.json)
          version=$(jq -r .version package.json)
          echo "pacname=$pacname" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV
          
      - name: Prepare artifact name
        id: vsix_name
        run: |
          pacname=${{ env.pacname }}  # If pacname was set in previous step to env, else define here
          version=${{ env.version }}  # Same for version
          artifact_vsix="${pacname}-vsce_v${version}.vsix"
          packaged_vsix="${pacname}-${version}.vsix"

          echo "packaged_vsix=$packaged_vsix" >> $GITHUB_ENV
          echo "artifact_vsix=$artifact_vsix" >> $GITHUB_ENV

          mkdir -p artifacts
          cp "$packaged_vsix" "artifacts/$artifact_vsix"
          ls -l artifacts

      - name: Publish release (version tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          name: Release v${{ env.version }}
          body_path: ./release.md
          files: artifacts
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release (latest tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Release latest
          body_path: ./release.md
          files: artifacts
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish VSCode Extension
        uses: lannonbr/vsce-action@4.0.0
        with:
          args: publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
