name: Publish VSCode

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - run: git submodule update --init ./core

      - run: npm run package

      #
      - name: Get version from package.json
        id: artifact
        run: |
          echo "pacname=$(jq -r .name package.json)" >> $GITHUB_OUTPUT
          echo "version=v$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Prepare artifact name
        id: vsix_name
        run: |
          echo "packaged_vsix=${{ steps.artifact.outputs.pacname }}-${{ steps.artifact.outputs.version }}.vsix" >> $GITHUB_OUTPUT
          echo "artifact_vsix=${{ steps.artifact.outputs.pacname }}-vsce_${{ steps.artifact.outputs.version }}.vsix" >> $GITHUB_OUTPUT

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vsix_name.outputs.artifact_vsix }}
          path: ${{ steps.vsix_name.outputs.packaged_vsix }}

      - name: Publish release (version tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.artifact.outputs.version }}
          name: Release ${{ steps.artifact.outputs.version }}
          body_path: ./release.md
          files: ${{ steps.vsix_name.outputs.packaged_vsix }}
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release (latest tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Release latest
          body_path: ./release.md
          files: ${{ steps.vsix_name.outputs.packaged_vsix }}
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish VSCode Extension
        uses: lannonbr/vsce-action@4.0.0
        with:
          args: publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
