name: Publish VSCode

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "22"

      - run: git submodule update --init ./core

      - run: npm run package

      - name: Get version from package.json
        id: artifact
        run: |
          pacname=$(jq -r .name package.json)
          version=$(jq -r .version package.json)
          echo "pacname=$pacname" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV

      - name: Prepare artifact name
        id: vsix_name
        run: |
          echo "packaged_vsix=${pacname}-${version}.vsix" >> $GITHUB_ENV
          echo "artifact_vsix=${pacname}-vsce_v${version}.vsix" >> $GITHUB_ENV

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_vsix }}
          path: ${{ env.packaged_vsix }}

      - name: Publish release (version tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.artifact.outputs.version }}
          name: Release v${{ steps.artifact.outputs.version }}
          body_path: ./release.md
          files: ${{ env.packaged_vsix }}
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release (latest tag)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Release latest
          body_path: ./release.md
          files: ${{ env.packaged_vsix }}
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish VSCode Extension
        uses: lannonbr/vsce-action@4.0.0
        with:
          args: publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
